### ISSUE TITLE
1.20 update?

### ISSUE THREAD

**Issue by Cr4fter-15** [florian-berger/painted-glowstone#1]
Is a update to 1.20 coming?

**Comment by florian-berger** [comment]
Hey,

the LibX mod is required by this modification. Since it is not yet available on CurseForge (see [here](https://www.curseforge.com/minecraft/mc-mods/libx/files)), it's not yet possible to upgrade. But as soon as the mod dependency is available, I will update the Painted Glowstone modification to Minecraft 1.20

**Comment by florian-berger** [comment]
Hi,

this mod was mainly created because I was missing the Ender IO Painging Machine, which allowed players to paint Glowstone blocks.

For Minecraft 1.20, [Ender IO came back](https://www.curseforge.com/minecraft/mc-mods/ender-io) (it's still in an early Alpha phase)! And with this, also the Painting Machine returned. So I won't update this mod to 1.20.

**Comment by florian-berger** [comment]
Because I was asked: I will update it for every **future** version, Ender IO is not existing for. There won't be any backports to older versions like 1.18!
